### ISSUE TITLE
Update python music maker path

### ISSUE THREAD

**Issue by jonxuxu** [sky-music/sky-music.github.io#2]
Hi there,
It seems that the path for command_line_player.py is now in `sky-python-music-sheet-maker/src/skymusic` instead of in `sky-python-music-sheet-maker/python` as listed in https://sky-music.github.io/make-your-own-sheet.html.

**Comment by tracey-le** [comment]
Oh that is right, I had forgotten to edit it. thank you for the heads up, I’ll fix it now

**Comment by tracey-le** [comment]
Updated here https://github.com/sky-music/sky-music.github.io/commit/81af1a37cb2f138d191ca8f981aaa7ad8bb95d2c
