### ISSUE TITLE
Transfer documentation

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-music.github.io#7]
The documentation from sky.bloomexperiment.com has to be transferred to this website.
Kai00 has agreed to arrange the layout and merge the text.

**Comment by tracey-le** [comment]
ok this is done now 
https://github.com/sky-music/sky-python-music-sheet-maker/wiki
https://github.com/sky-music/sky-music.github.io/wiki

**Comment by tracey-le** [comment]
and the sidebar on https://sky-music.github.io/
