### ISSUE TITLE
Split sheetDarkModeScript

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-music.github.io#8]
split sheetDarkModeScript.js into:

* sheetDarkModeScript
* sheetDownloadScript

and add a script tag to the existing sheets accordingly

The new music-sheet-maker already assumes this change.

**Comment by tracey-le** [comment]
this is done by Specy now 

https://github.com/sky-music/sky-music.github.io/commit/5bbb412c5e26c4021ee23d8f2b5aa9b9660b8c18
